language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6-dev" # 3.6 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install coveralls
# command to run tests
script:
  - py.test test.py
  - flake8 .
  - coverage run test.py
after_success:
  - coveralls
